# Copyright 2024 PKU-Alignment Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
#
# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.8 conda env create --file conda-recipe.yaml
#

name: safe-sora
channels:
  - huggingface
  - pytorch
  - nvidia/label/cuda-12.1.0
  - defaults
  - conda-forge
dependencies:
  - python = 3.11
  - pip

  - pytorch::pytorch >= 2.0
  - pytorch::pytorch-mutex =*=*cuda*
  - pytorch::torchvision
  - transformers >= 4.42
  - datasets
  - tokenizers >= 0.19
  - sentencepiece
  - tensorboard
  - wandb
  - pip:
      - accelerate
      - deepspeed
      - decord
      - opencv-python

  - nvidia/label/cuda-12.1.0::cuda-toolkit = 12.1

  - matplotlib-base
  - rich
  - tqdm
  - typing-extensions
  - bitsandbytes
  - av
  - einops
  - peft
